import { Atividade } from './atividade';

export type CliforFuncoes = {
  id: number;
  descricao: string;
  flag_ativo: boolean;
};

export type PessoaFisica = {
  idcidadenascimento: number;
  dtnascimento: Date;
  dtadmissao: Date;
  dtemissaorg: Date;
  rg: string;
  emissorrg: string;
  profissao: string;
  empresatrabalho: string;
  endercomercial: string;
  tipoestadocivil: string;
  valsalarioatual: number;
  temporesidencia: string;
  tiporesidencia: string;
  qtddependentes: number;
  nomepai: string;
  tipoendercorresp: string;
  nomemae: string;
  valrendafamiliar: number;
  foto: string;
  chapafolhapgto: string;
  fonetrabalho: string;
  valaluguel: number;
  idcliforentrega: number;
  tiporeligiao: string;
  timefutebol: string;
  sexo: string;
  nomeconjuge: string;
  dtnascconjuge: Date;
  profissaoconjuge: string;
  empresaconjuge: string;
  dtadmissaoconjuge: Date;
  contatoconjuge: string;
  renda: number;
  cpfconjuge: string;
};

export type ClienteDependente = {
  id: number;
  clifor_id: number;
  parentesco_id: number;
  descrautorizado: string;
  cnpjcpf: string;
  rg: string;
  emissorRg: string;
  tipograudependencia: string;
  datanascimento: Date;
  tiposexo: string;
  email: string;
  estadoCivil: string;
  escolaridade: string;
  tipo: string;
  percentual: number;
  pensionista: string;
  renda: string;
  agencia: string;
  conta: string;
  especial: string;
  status: string;
  falecido: string;
  dataFalecimento: Date;
  numeroCertidaoObito: string;
  endereco: string;
  numero: string;
  cep: string;
  complemento: string;
  telefone: string;
};

export type ClienteFornecedorAnexo = {
  id: number;
  arquivo: string;
  file?: File | null;
  name?: string;
  size?: number;
};

export type ClienteFornecedor = {
  dependente: ClienteDependente[];
  pessoa: PessoaFisica;
  anexo: ClienteFornecedorAnexo[];
  id: number;
  nome: string;
  atividade_id: number;
  atividade: Atividade;
  cnpjcpf: string;
  ufcobranca: string;
  ufclifor: string;
  endereco: string;
  bairro: string;
  city: string;
  code: string;
  nro: string;
  refbancaria: string;
  refcomercial: string;
  refpessoal: string;
  endercobranca: string;
  refseproc: string;
  bairrocobranca: string;
  flagavisarvcto: boolean;
  perdesconto: number;
  dtrevisaocadastral: Date;
  dtcadastro: Date;
  fonefax: string;
  fone1: string;
  fone2: string;
  fonecelular: string;
  numcartaomag: string;
  diavencimento: number;
  vallimitecredito: number;
  vallimiteconvenio: number;
  vallimiteseguracachq: number;
  dtvalidadecartao: Date;
  tipocadastro: string;
  inscrestadual: string;
  suframa: string;
  obsgeral: string;
  senhaconvenio: number;
  placatransporte: string;
  nomefantasia: string;
  email: string;
  nomecontato1: string;
  diasentrega: number;
  tiporegimetributacao: string;
  nomecontato2: string;
  perredtributacao: number;
  diasprazo: number;
  cepcobranca: number;
  tipofisicajuridica: string;
  perdescontogeral: number;
  diasprazo1: number;
  flagfretecif: boolean;
  diasprazo2: number;
  diasprazo3: number;
  diasprazo4: number;
  flaginativo: boolean;
  valfaturamento: number;
  flagnaoconschqserasa: boolean;
  dtultimaalteracao: Date;
  dtinicialpromocao: Date;
  dtfinalpromocao: Date;
  tiporegimetribfederal: string;
  flagpontua: boolean;
  perdescbaixaduplantecip: number;
  peracrescimooverp: number;
  url: string;
  dtcanccontrato: Date;
  flagcalculasubstituicao: boolean;
  flaglivrecomercio: boolean;
  flagdebitoautomaticohrs: boolean;
  scorecliente: number;
  flag_ativo: boolean;
  flagcalculasubstituicaoforauf: boolean;
  idgrupoeconomico: number;
  cnh: string;
  datavalidacnh: Date;
  cnhcategoria: string;
  foto: string;
  obsfinanceiro: string;
};
