export type CliforFuncoes = {
  id: number;
  descricao: string;
  flag_ativo: boolean;
};

export type PessoaFisica = {
  idcidadenascimento: number;
  dtnascimento: Date;
  dtadmissao: Date;
  dtemissaorg: Date;
  rg: string;
  emissorrg: string;
  profissao: string;
  empresatrabalho: string;
  endercomercial: string;
  tipoestadocivil: string;
  valsalarioatual: number;
  temporesidencia: string;
  tiporesidencia: string;
  qtddependentes: number;
  nomepai: string;
  tipoendercorresp: string;
  nomemae: string;
  valrendafamiliar: number;
  foto: string;
  chapafolhapgto: string;
  fonetrabalho: string;
  valaluguel: number;
  idcliforentrega: number;
  tiporeligiao: string;
  timefutebol: string;
  sexo: string;
  nomeconjuge: string;
  dtnascconjuge: Date;
  profissaoconjuge: string;
  empresaconjuge: string;
  dtadmissaoconjuge: Date;
  contatoconjuge: string;
  renda: number;
  cpfconjuge: string;
};

export type ClienteDependente = {
  id: number;
  clifor_id: number;
  parentesco_id: number;
  descrautorizado: string;
  cnpjcpf: string;
  rg: string;
  emissorRg: string;
  tipograudependencia: string;
  datanascimento: Date;
  tiposexo: string;
  email: string;
  estadoCivil: string;
  escolaridade: string;
  tipo: string;
  percentual: number;
  pensionista: string;
  renda: string;
  agencia: string;
  conta: string;
  especial: string;
  status: string;
  falecido: string;
  dataFalecimento: Date;
  numeroCertidaoObito: string;
  endereco: string;
  numero: string;
  cep: string;
  complemento: string;
  telefone: string;
};

export type ClienteFornecedorAnexo = {
  id: number;
  arquivo: string;
  file?: File | null;
  name?: string;
  size?: number;
};

export type Pessoas = {
  id: number;
  nome: string;
  cpf: string;
  atividade_id: number;
  uf: string;
  endereco: string;
  bairro: string;
  city: string;
  code: string;
  nro: string;
  refpessoal: string;
  dtcadastro: Date;
  fonefax: string;
  fone1: string;
  fone2: string;
  fonecelular: string;
  diavencimento: number;
  tipocadastro: string;
  inscrestadual: string;
  obsgeral: string;
  nomemae: string;
  titulo: string;
  dtexpedicao: Date;
  zona: string;
  secao: string;
  email: string;
  flaginativo: boolean;
  dtultimaalteracao: Date;
  flagpontua: boolean;
  flag_ativo: boolean;
  foto: string;
  rg: string;
  emissorrg: string;
  dtexpedicaorg: Date;
  dtnascimento: Date;
};
